name: HTML to PDF

on: [push]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./CV2/index.html
          outputFile: ./resume.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'

      - name: Commit files
        run: |
          git config --local user.name "githubactions"
          git config --local user.email "actions@github.com"
          git add ./resume.pdf
          git commit -m "Auto add pdf file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
